/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicegame.UserInterface;

import dicegame.Account;
import dicegame.AcctValue;
import dicegame.Die;
import dicegame.Game;
import static dicegame.Game.getNumberOfDice;
import static dicegame.Game.getNumberOfSides;
import static dicegame.Game.promptPlayerName;
import static dicegame.Game.promptStartingAcctVal;
import static dicegame.Game.promptWager;
import static dicegame.Game.retrieveWager;
import dicegame.Player;
import java.util.Locale;
import java.util.Set;

/**
 *
 * @author Wesley
 */
public class DiceGameUI extends javax.swing.JFrame {

    private String playerName;
    private AcctValue initialAcctValue;
    private Account account;
    private Player player;
    private Game game;
    private String aWager;
    private int numOfDice;
    private int numOfSides;
    private String a = null, b = null, c = null, d = null;
    private final int winPercentileLB = 5;
    private final int winPercentileUB = 40;
    private final int losePercentileLB = 41;
    private final int losePercentileUB = 85;
    /**
     * Creates new form DiceGameUI
     */
    public DiceGameUI() { 
        
        //Initialize a game form
        initComponents();
        
        this.btnRoll.setEnabled(false);
        this.btnPush.setEnabled(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        pnlConfig = new javax.swing.JPanel();
        pnlDice = new javax.swing.JPanel();
        lblNumDice = new javax.swing.JLabel();
        lblNumSides = new javax.swing.JLabel();
        txtNumDice = new javax.swing.JTextField();
        txtNumSides = new javax.swing.JTextField();
        lblRollDice = new javax.swing.JLabel();
        btnRoll = new javax.swing.JButton();
        lblWager = new javax.swing.JLabel();
        txtWager = new javax.swing.JTextField();
        btnPush = new javax.swing.JButton();
        pnlPlayer = new javax.swing.JPanel();
        txtInitialAcctValue = new javax.swing.JTextField();
        txtPlayerName = new javax.swing.JTextField();
        lblInitialAcctValue = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblSubmit = new javax.swing.JLabel();
        lblCurrentAcctValue = new javax.swing.JLabel();
        lblNumericAccountValue = new javax.swing.JLabel();
        pnlResults = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResults = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlConfig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlDice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDice.setToolTipText("Roll Configuration");
        pnlDice.setName("Roll Configuration"); // NOI18N

        lblNumDice.setText("Number of Dice:");

        lblNumSides.setText("Number of Sides:");

        txtNumDice.setText("6");

        txtNumSides.setText("6");
        txtNumSides.setActionCommand("<Not Set>");

        lblRollDice.setText("Roll Dice:");

        btnRoll.setText("Roll!");
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });

        lblWager.setText("Wager:");

        txtWager.setText("1000");

        btnPush.setText("Push!");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDiceLayout = new javax.swing.GroupLayout(pnlDice);
        pnlDice.setLayout(pnlDiceLayout);
        pnlDiceLayout.setHorizontalGroup(
            pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiceLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDiceLayout.createSequentialGroup()
                        .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumSides)
                            .addComponent(lblWager)
                            .addComponent(lblNumDice))
                        .addGap(28, 28, 28)
                        .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumSides, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumDice, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWager, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDiceLayout.createSequentialGroup()
                        .addComponent(lblRollDice)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPush, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlDiceLayout.setVerticalGroup(
            pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiceLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumDice)
                    .addComponent(txtNumDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSides)
                    .addComponent(txtNumSides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWager)
                    .addComponent(txtWager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRollDice)
                    .addComponent(btnRoll)
                    .addComponent(btnPush))
                .addGap(7, 7, 7))
        );

        pnlPlayer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPlayer.setToolTipText("Player configuration");

        txtInitialAcctValue.setText("100000.23");
        txtInitialAcctValue.setName("txtInitialAcctValue"); // NOI18N

        txtPlayerName.setText("Name");
        txtPlayerName.setToolTipText("");
        txtPlayerName.setName("txtPlayerName"); // NOI18N
        txtPlayerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayerNameActionPerformed(evt);
            }
        });

        lblInitialAcctValue.setText("Initial Account Value:");
        lblInitialAcctValue.setName("lblInitialAcctValue"); // NOI18N

        lblPlayerName.setText("Player Name:");
        lblPlayerName.setName("lblPlayerName"); // NOI18N

        btnSubmit.setText("Submit");
        btnSubmit.setName("btnSubmit"); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblSubmit.setText("Submit:");
        lblSubmit.setName("lblSubmit"); // NOI18N

        javax.swing.GroupLayout pnlPlayerLayout = new javax.swing.GroupLayout(pnlPlayer);
        pnlPlayer.setLayout(pnlPlayerLayout);
        pnlPlayerLayout.setHorizontalGroup(
            pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPlayerName)
                    .addComponent(lblInitialAcctValue)
                    .addComponent(lblSubmit))
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlayerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInitialAcctValue, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPlayerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPlayerLayout.setVerticalGroup(
            pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayerName))
                .addGap(34, 34, 34)
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInitialAcctValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInitialAcctValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubmit)
                    .addComponent(btnSubmit))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        lblCurrentAcctValue.setText("Current Account Value:");
        lblCurrentAcctValue.setToolTipText("");
        lblCurrentAcctValue.setName("lblPlayerName"); // NOI18N

        lblNumericAccountValue.setText("0.00");
        lblNumericAccountValue.setToolTipText("");
        lblNumericAccountValue.setName("lblPlayerName"); // NOI18N

        javax.swing.GroupLayout pnlConfigLayout = new javax.swing.GroupLayout(pnlConfig);
        pnlConfig.setLayout(pnlConfigLayout);
        pnlConfigLayout.setHorizontalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfigLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblCurrentAcctValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumericAccountValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConfigLayout.setVerticalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentAcctValue)
                    .addComponent(lblNumericAccountValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        pnlResults.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAreaResults.setColumns(20);
        txtAreaResults.setRows(5);
        txtAreaResults.setToolTipText("Results area");
        jScrollPane1.setViewportView(txtAreaResults);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed
        // Rolls dice
        
        //create an account value object
        AcctValue value2 = new AcctValue(-1,-1, false);
        
        //get wager
        value2 = retrieveWager(this.txtWager.getText());
            
        Roll(value2);
    }//GEN-LAST:event_btnRollActionPerformed
    
    
    public void Roll(AcctValue value2){
        
        //get number of dice
        int numberOfDice = getNumberOfDice(this.txtNumDice.getText());
        
        //get number of sides 
        int numberOfSides = getNumberOfSides(this.txtNumSides.getText());
        
        //define game scores
        this.game.defineScores(numberOfDice, numberOfSides, this.winPercentileLB, this.winPercentileUB, this.losePercentileLB, this.losePercentileUB );
        
        //set set dice count
        this.game.resetDice();
        
        //Make dice
        this.game.makeDice(numberOfDice, numberOfSides);
        
        //set player wager
        this.player.setWager(value2);
        
        int tv = 0;
        //roll each die
        for (Die temp : game.getDice()) {

            //Rolls die
            temp.rollDie();

            //sums values
            tv = tv + temp.getCurrentValue();

        }
        
        //assign the target value
        this.game.setTargetValue(tv); 

        //Verify the score
        game.verifyScore();
        
        if(game.getWin() == 1 && game.getPush()!= true){
            //Won, retrieve the wager and update the players account with the wager amount
            AcctValue acctVal  = player.getWager();
            player.updateAccount(-acctVal.getDollars(), -acctVal.getCents());
            game.incrementWins();
            game.setWin(0);
            
        }
        else if(game.getWin() == 1 && game.getPush() == true){
            //Do nothing
            game.setWin(0);
            game.incrementPushes();
            game.setPush(false);
        }
        else if(game.getWin() == -1 && game.getPush()!= true){
            //Otherwise lost, retrieve the wager
            AcctValue acctVal  = player.getWager();

            //flip it negative
            player.updateAccount(acctVal.getDollars(), acctVal.getCents());

            game.incrementLosses();

            game.setWin(0);
        }
        else if(game.getPush() ==  true){
            game.incrementPushes();
            game.setWin(0);
            game.setPush(false);
        }
        else{
            
            System.out.println("===========Null game==========");
        }
        
        //finish
        String txt = game.reportGameText();
        
        //print result
        printTextField(txt);
        
        this.lblNumericAccountValue.setText(this.player.getAccount());
    }
    
    public void printTextField(String text) {
        this.txtAreaResults.append(text);
    }
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Submits player info to the game
        this.playerName = promptPlayerName(this.txtPlayerName.getText());
        this.initialAcctValue = promptStartingAcctVal(this.txtInitialAcctValue.getText());
        
        //Set up initial information
        //set up a game
        Account acct = new Account(Locale.US, this.initialAcctValue.getUnits());
        this.player = new Player(this.playerName, acct);
        this.game = new Game(player);
        
        //disable controls after inputing initial info
        this.txtPlayerName.setEnabled(false);
        this.txtInitialAcctValue.setEnabled(false);
        this.btnSubmit.setEnabled(false);
        this.lblNumericAccountValue.setText(acct.getAmount());
        this.btnRoll.setEnabled(true);
        this.btnPush.setEnabled(true);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerNameActionPerformed

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        //indicate a push
        this.game.setPush(true);
        
        //create an account value object
        AcctValue value2 = new AcctValue(-1,-1, false);
        
        //get wager
        value2 = retrieveWager("0.00");
        
        Roll(value2);
    }//GEN-LAST:event_btnPushActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnRoll;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentAcctValue;
    private javax.swing.JLabel lblInitialAcctValue;
    private javax.swing.JLabel lblNumDice;
    private javax.swing.JLabel lblNumSides;
    private javax.swing.JLabel lblNumericAccountValue;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblRollDice;
    private javax.swing.JLabel lblSubmit;
    private javax.swing.JLabel lblWager;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlDice;
    private javax.swing.JPanel pnlPlayer;
    private javax.swing.JPanel pnlResults;
    private javax.swing.JTextArea txtAreaResults;
    private javax.swing.JTextField txtInitialAcctValue;
    private javax.swing.JTextField txtNumDice;
    private javax.swing.JTextField txtNumSides;
    private javax.swing.JTextField txtPlayerName;
    private javax.swing.JTextField txtWager;
    // End of variables declaration//GEN-END:variables
}
