/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dicegame.UserInterface;

import dicegame.Account;
import dicegame.AcctValue;
import dicegame.CurrencyVerifier;
import dicegame.Die;
import dicegame.Game;
import dicegame.Input;
//import static dicegame.Input.getNumberOfDice;
//import static dicegame.Input.getNumberOfSides;
import static dicegame.Input.getPlayerName;
import static dicegame.Input.getStartingAcctVal;
import static dicegame.Input.getWager;
import dicegame.LettersVerifier;
//import dicegame.NumericVerifier;
import dicegame.Player;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 * The class that is the view for the program
 * @author Wesley
 */
public class DiceGameUI extends javax.swing.JFrame {

    private String playerName;
    private AcctValue initialAcctValue;
    private Player player;
    private Game game;
    private String a = null, b = null, c = null, d = null;
    private final int winPercentileLB = 5;
    private final int winPercentileUB = 40;
    private final int losePercentileLB = 41;
    private final int losePercentileUB = 85;
    /**
     * Creates new form DiceGameUI
     */
    public DiceGameUI() { 
        
        //Initialize a game form
        initComponents();
        
        //Cannot roll until user has entered requisite information
        this.btnSubmit.setEnabled(false);
        this.btnRoll.setEnabled(false);
        this.btnPush.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        pnlConfig = new javax.swing.JPanel();
        pnlDice = new javax.swing.JPanel();
        lblNumDice = new javax.swing.JLabel();
        lblNumSides = new javax.swing.JLabel();
        lblRollDice = new javax.swing.JLabel();
        btnRoll = new javax.swing.JButton();
        lblWager = new javax.swing.JLabel();
        btnPush = new javax.swing.JButton();
        txtFWager = new JFormattedTextField();
        txtFWager.setInputVerifier(new CurrencyVerifier(btnRoll));
        txtFWager.addPropertyChangeListener("value", new FormattedTextFieldListener());
        slNumDice = new javax.swing.JSlider();
        slNumDice.addChangeListener(new SliderListener());
        slNumSides = new javax.swing.JSlider();
        slNumSides.addChangeListener(new SliderListener());
        lblNumDiceVal = new javax.swing.JLabel();
        lblNumDiceVal.setText(String.valueOf(slNumDice.getValue()));
        lblNumSidesVal = new javax.swing.JLabel();
        lblNumSidesVal.setText(String.valueOf(slNumSides.getValue()));
        pnlPlayer = new javax.swing.JPanel();
        lblInitialAcctValue = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblSubmit = new javax.swing.JLabel();
        txtFInitialAcctValue = new JFormattedTextField();
        txtFInitialAcctValue.setInputVerifier(new CurrencyVerifier(btnSubmit));
        txtFInitialAcctValue.addPropertyChangeListener("value", new FormattedTextFieldListener());
        txtFPlayerName = new JFormattedTextField();
        txtFPlayerName.setInputVerifier(new LettersVerifier());
        lblCurrentAcctValue = new javax.swing.JLabel();
        lblNumericAccountValue = new javax.swing.JLabel();
        pnlResults = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResults = new javax.swing.JTextArea();
        txtAreaResults.setEnabled(false);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlConfig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlDice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDice.setToolTipText("Roll configuration");
        pnlDice.setName("Roll Configuration"); // NOI18N

        lblNumDice.setText("Number of Dice:");

        lblNumSides.setText("Number of Sides:");

        lblRollDice.setText("Roll Dice:");

        btnRoll.setText("Roll!");
        btnRoll.setToolTipText("Becomes available after setting a valid wager");
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });

        lblWager.setText("Wager:");

        btnPush.setText("Push!");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        txtFWager.setText("Wager");
        txtFWager.setToolTipText("Enter your wager here (positive integer)");
        txtFWager.setName("txtjFormattedWager"); // NOI18N
        txtFWager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFWagerActionPerformed(evt);
            }
        });

        slNumDice.setMaximum(90000);
        slNumDice.setMinimum(1);
        slNumDice.setToolTipText("");
        slNumDice.setValue(90000);

        slNumSides.setMaximum(90000);
        slNumSides.setMinimum(6);
        slNumSides.setToolTipText("");
        slNumSides.setValue(6);

        lblNumDiceVal.setText("90000");

        lblNumSidesVal.setText("6");

        javax.swing.GroupLayout pnlDiceLayout = new javax.swing.GroupLayout(pnlDice);
        pnlDice.setLayout(pnlDiceLayout);
        pnlDiceLayout.setHorizontalGroup(
            pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiceLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDiceLayout.createSequentialGroup()
                        .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(slNumDice, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slNumSides, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDiceLayout.createSequentialGroup()
                                .addComponent(lblRollDice)
                                .addGap(18, 18, 18)
                                .addComponent(btnRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPush, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(pnlDiceLayout.createSequentialGroup()
                        .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumSides)
                            .addComponent(lblNumDice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDiceLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblWager)))
                        .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDiceLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txtFWager, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDiceLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDiceLayout.createSequentialGroup()
                                        .addComponent(lblNumDiceVal)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDiceLayout.createSequentialGroup()
                                        .addComponent(lblNumSidesVal)
                                        .addGap(28, 28, 28))))))))
        );
        pnlDiceLayout.setVerticalGroup(
            pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumDice)
                    .addComponent(lblNumDiceVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slNumDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSides)
                    .addComponent(lblNumSidesVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slNumSides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWager)
                    .addComponent(txtFWager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlDiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRollDice)
                    .addComponent(btnRoll)
                    .addComponent(btnPush))
                .addGap(7, 7, 7))
        );

        pnlPlayer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPlayer.setToolTipText("Player configuration");

        lblInitialAcctValue.setText("Initial Account Value:");
        lblInitialAcctValue.setName("lblInitialAcctValue"); // NOI18N

        lblPlayerName.setText("Player Name:");
        lblPlayerName.setName("lblPlayerName"); // NOI18N

        btnSubmit.setText("Submit");
        btnSubmit.setToolTipText("Valid initial account value will enable submit.");
        btnSubmit.setFocusPainted(false);
        btnSubmit.setName("btnSubmit"); // NOI18N
        btnSubmit.setRequestFocusEnabled(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblSubmit.setText("Submit:");
        lblSubmit.setName("lblSubmit"); // NOI18N

        txtFInitialAcctValue.setText("Account Value");
        txtFInitialAcctValue.setToolTipText("Starting Account Value (positive integer)");
        txtFInitialAcctValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFInitialAcctValueActionPerformed(evt);
            }
        });

        txtFPlayerName.setText("Name");
        txtFPlayerName.setToolTipText("Enter player name here.");

        javax.swing.GroupLayout pnlPlayerLayout = new javax.swing.GroupLayout(pnlPlayer);
        pnlPlayer.setLayout(pnlPlayerLayout);
        pnlPlayerLayout.setHorizontalGroup(
            pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayerLayout.createSequentialGroup()
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPlayerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPlayerName)
                            .addComponent(lblInitialAcctValue)
                            .addComponent(lblSubmit))
                        .addGap(26, 26, 26)
                        .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFInitialAcctValue)
                            .addComponent(txtFPlayerName)))
                    .addGroup(pnlPlayerLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPlayerLayout.setVerticalGroup(
            pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayerName)
                    .addComponent(txtFPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInitialAcctValue)
                    .addComponent(txtFInitialAcctValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubmit)
                    .addComponent(btnSubmit))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblCurrentAcctValue.setText("Current Account Value:");
        lblCurrentAcctValue.setToolTipText("");
        lblCurrentAcctValue.setName("lblPlayerName"); // NOI18N

        lblNumericAccountValue.setText("0.00");
        lblNumericAccountValue.setToolTipText("");
        lblNumericAccountValue.setName("lblPlayerName"); // NOI18N

        javax.swing.GroupLayout pnlConfigLayout = new javax.swing.GroupLayout(pnlConfig);
        pnlConfig.setLayout(pnlConfigLayout);
        pnlConfigLayout.setHorizontalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblCurrentAcctValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumericAccountValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConfigLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        pnlConfigLayout.setVerticalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentAcctValue)
                    .addComponent(lblNumericAccountValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        pnlResults.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAreaResults.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaResults.setColumns(20);
        txtAreaResults.setRows(5);
        txtAreaResults.setToolTipText("Results area");
        txtAreaResults.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAreaResults.setEnabled(false);
        jScrollPane1.setViewportView(txtAreaResults);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("After entering a valid initial account value (a positive integer)");

        jLabel2.setText("press tab to move to the next control.");

        jLabel3.setText("After entering a valid Wager press tab to enable roll button.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)))
                .addGap(53, 53, 53)
                .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed
        // Rolls dice
        
        //create an account value object
        AcctValue value2 = new AcctValue(-1,-1);
        
        //get wager
        value2 = getWager(this.txtFWager.getText());
            
        Roll(value2);
    }//GEN-LAST:event_btnRollActionPerformed
    
    /**
     * Rolls the dice for the game since the user interacts with the UI the UI is effectively 'rolling'
     * @param value2 an account value
     */
    public void Roll(AcctValue value2){
        
        //get number of dice
        int numberOfDice = this.slNumDice.getValue();
        
        //get number of sides 
        int numberOfSides = this.slNumSides.getValue();
        
        //define game scores
        this.game.defineScores(numberOfDice, numberOfSides, this.winPercentileLB, this.winPercentileUB, this.losePercentileLB, this.losePercentileUB );
        
        //set set dice count
        this.game.resetDice();
        
        //Make dice
        this.game.makeDice(numberOfDice, numberOfSides);
        
        //set player wager
        this.player.setWager(value2);
        
        int tv = 0;
        //roll each die
        for (Die temp : game.getDice()) {

            //Rolls die
            temp.rollDie();

            //sums values
            tv = tv + temp.getCurrentValue();

        }
        
        //assign the target value
        this.game.setTargetValue(tv); 

        //Verify the score
        game.verifyScore();
        
        if(game.getWin() == 1 && game.getPush()!= true){
            //Won, retrieve the wager and update the players account with the wager amount
            AcctValue acctVal  = player.getWager();
            player.updateAccount(-acctVal.getDollars(), -acctVal.getCents());
            game.incrementWins();
            game.setWin(0);
            
        }
        else if(game.getWin() == 1 && game.getPush() == true){
            //Do nothing
            game.setWin(0);
            game.incrementPushes();
            game.setPush(false);
        }
        else if(game.getWin() == -1 && game.getPush()!= true){
            //Otherwise lost, retrieve the wager
            AcctValue acctVal  = player.getWager();

            //flip it negative
            player.updateAccount(acctVal.getDollars(), acctVal.getCents());

            game.incrementLosses();

            game.setWin(0);
        }
        else if(game.getPush() ==  true){
            game.incrementPushes();
            game.setWin(0);
            game.setPush(false);
        }
        else{
            //value outside of win or lose
            printTextField("\n===========Null game==========");
        }
        
        //finish
        String txt = game.reportGameText();
        
        //print result
        printTextField(txt);
        
        this.lblNumericAccountValue.setText(this.player.getAccount());
    }
    
    /**
     * Gets the Initial Account Value Field
     * @return JFormattedTextField JComponent
     */
    public static JFormattedTextField getInitialAcctValueField(){
        return txtFInitialAcctValue;
    }
    
    /**
     * Gets the Submit Button JComponent
     * @return JButton JComponent
     */
    public static JButton getSubmitBtn(){
        return btnSubmit;
    }
    
    /**
     * Gets the Wager Value JFormattedTextField
     * @return JFormattedTextField JComponent
     */
    public static JFormattedTextField getWagerValueField(){
        return txtFWager;
    }
    
    /**
     * Gets the Roll Button JComponent
     * @return JButton JComponent
     */
    public static JButton getRollBtn(){
        return btnRoll;
    }
    
    /**
     * Gets the Number of Dice Slider JComponent
     * @return Slider JComponent
     */
    public static JSlider getNumDiceSlider(){
        return slNumDice;
    }
    
    /**
     * Gets the Number of Dice Label JComponent
     * @return JLabel JComponent
     */
    public static JLabel getNumDiceLbl(){
        return lblNumDiceVal;
    }
    
    /**
     * Gets the number of sides JLabel object
     * @return JLabel Jcomponent
     */
    public static JLabel getNumSidesLbl(){
        return lblNumSidesVal;
    }
    
    /**
     * gets the number of sides slider Jcomponent
     * @return JSlider component
     */
    public static JSlider getNumSidesSlider(){
        return slNumSides;
    }
    
    /**
     * Appends text to the results text area
     * @param text as a string
     */
    public void printTextField(String text) {
        this.txtAreaResults.append(text);
    }
     
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Submits player info to the game
        this.playerName = getPlayerName(this.txtFPlayerName.getText());
        this.initialAcctValue = getStartingAcctVal(this.txtFInitialAcctValue.getText());
        
        //Set up initial information
        //set up a game
        Account acct = new Account(Locale.US, this.initialAcctValue.convertPennies());
        this.player = new Player(this.playerName, acct);
        this.game = new Game(player);
        
        //disable controls after inputing initial info
        this.txtFPlayerName.setEnabled(false);
        this.txtFInitialAcctValue.setEnabled(false);
        this.btnSubmit.setEnabled(false);
        this.lblNumericAccountValue.setText(acct.getAmount());
        //this.btnRoll.setEnabled(true);
        this.btnPush.setEnabled(true);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        //indicate a push
        this.game.setPush(true);
        
        //create an account value object
        AcctValue value2 = new AcctValue(-1,-1);
        
        //get wager
        value2 = Input.getWager("0.00");
        
        Roll(value2);
    }//GEN-LAST:event_btnPushActionPerformed

    private void txtFWagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFWagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFWagerActionPerformed

    private void txtFInitialAcctValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFInitialAcctValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFInitialAcctValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceGameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPush;
    private static javax.swing.JButton btnRoll;
    private static javax.swing.JButton btnSubmit;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentAcctValue;
    private javax.swing.JLabel lblInitialAcctValue;
    private javax.swing.JLabel lblNumDice;
    private static javax.swing.JLabel lblNumDiceVal;
    private javax.swing.JLabel lblNumSides;
    private static javax.swing.JLabel lblNumSidesVal;
    private javax.swing.JLabel lblNumericAccountValue;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblRollDice;
    private javax.swing.JLabel lblSubmit;
    private javax.swing.JLabel lblWager;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlDice;
    private javax.swing.JPanel pnlPlayer;
    private javax.swing.JPanel pnlResults;
    private static javax.swing.JSlider slNumDice;
    private static javax.swing.JSlider slNumSides;
    private javax.swing.JTextArea txtAreaResults;
    private static javax.swing.JFormattedTextField txtFInitialAcctValue;
    private javax.swing.JFormattedTextField txtFPlayerName;
    private static javax.swing.JFormattedTextField txtFWager;
    // End of variables declaration//GEN-END:variables
}
